[[main]]
  identifier = "about"
  name = "关于我"
  url = "about"
  weight = 3

[[main]]
  identifier = "archive"
  name = "时光机"
  url = "archive"
  weight = 2

[[main]]
  identifier = "posts"
  name = "笔记"
  url = "posts"
  weight = 1